<<<<<<< HEAD
services:
  - type: web
    name: rentease-web
    env: static
    staticPublishPath: dist
    buildCommand: npm install && npm run build
    envVars:
      - key: NODE_VERSION
=======
services:
  - type: web
    name: rentease-web
    env: static
    staticPublishPath: dist
    buildCommand: npm install && npm run build
    envVars:
      - key: NODE_VERSION
>>>>>>> ff04465 (Initial commit)
        value: 18 